apiVersion: v1
kind: Service
metadata:
  name: argocd-app-service
  namespace: default
spec:
  selector:
    app: argocd-app
  type: NodePort
  ports:
    - name: argocd-app-service
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
